# GA: api-throttling. A stage-wide ceiling, one usage plan per channel, and an alarm when clients get throttled.
resource "aws_api_gateway_method_settings" "all" {
  # checkov:skip=CKV_AWS_225:Answers are per shopper and per conversation; a response cache would serve one shopper's answer to another.
  rest_api_id = var.rest_api_id
  stage_name  = var.stage_name
  method_path = "*/*"

  settings {
    metrics_enabled        = true
    logging_level          = "ERROR"
    throttling_rate_limit  = var.stage_rate_limit
    throttling_burst_limit = var.stage_burst_limit
  }
}

resource "aws_api_gateway_usage_plan" "channel" {
  for_each = var.channels

  name        = "${var.name_prefix}-${each.key}"
  description = "Quota for the ${each.key} channel"

  api_stages {
    api_id = var.rest_api_id
    stage  = var.stage_name
  }

  throttle_settings {
    rate_limit  = each.value.rate_limit
    burst_limit = each.value.burst_limit
  }

  quota_settings {
    limit  = each.value.daily_quota
    period = "DAY"
  }
}

# Key values are generated by API Gateway and never appear in this configuration.
resource "aws_api_gateway_api_key" "channel" {
  for_each = var.channels

  name    = "${var.name_prefix}-${each.key}"
  enabled = true
}

resource "aws_api_gateway_usage_plan_key" "channel" {
  for_each = var.channels

  key_id        = aws_api_gateway_api_key.channel[each.key].id
  key_type      = "API_KEY"
  usage_plan_id = aws_api_gateway_usage_plan.channel[each.key].id
}

resource "aws_cloudwatch_metric_alarm" "throttled" {
  alarm_name          = "${var.name_prefix}-4xx-rate"
  alarm_description   = "Clients receive 4XX responses (throttling or quota) on more than 5% of requests."
  namespace           = "AWS/ApiGateway"
  metric_name         = "4XXError"
  statistic           = "Average"
  period              = 300
  evaluation_periods  = 3
  threshold           = 0.05
  comparison_operator = "GreaterThanThreshold"
  treat_missing_data  = "notBreaching"
  alarm_actions       = [var.alarm_topic_arn]

  dimensions = {
    ApiName = var.name_prefix
    Stage   = var.stage_name
  }
}
